// =============================================================================
// Validation/HallucinationRegressionTests.cs — anti-hallucination regression tests
// =============================================================================
// Explicit tests for previously observed hallucination patterns:
//   - Hallucinated section titles
//   - Ontology completion
//   - Disconnected context sections
//   - Propagation-only entities
//   - Ungrounded traversal paths
// =============================================================================

using Core.Context;

namespace Core.Validation;

public static class HallucinationRegressionTests
{
    public static IReadOnlyList<SemanticRegressionCase> BuildTestSuite()
    {
        var suite = new GroundingRegressionSuite();

        RegisterHallucinatedTitleTests(suite);
        RegisterOntologyCompletionTests(suite);
        RegisterDisconnectedContextTests(suite);
        RegisterPropagationOnlyTests(suite);
        RegisterUngroundedPathTests(suite);

        return suite.Cases;
    }

    private static void RegisterHallucinatedTitleTests(GroundingRegressionSuite suite)
    {
        var forbiddenTitles = new[]
        {
            "business logic abstraction",
            "core domain concept",
            "primary workflow",
            "enterprise pattern",
            "architectural pattern",
            "ontology completion",
            "smart compression",
            "auto-generated summary",
        };

        foreach (var forbidden in forbiddenTitles)
        {
            suite.Register(new SemanticRegressionCase
            {
                CaseId = $"anti-hall-title-{forbidden.GetHashCode():X8}"[..16],
                Name = $"No Hallucinated Title: \"{forbidden}\"",
                Description = $"Verify that the title \"{forbidden}\" never appears in any context section.",
                Category = RegressionCategory.Hallucination,
                Query = new Retrieval.Retrieval.RetrievalQuery { Query = "API flow analysis", TopK = 10 },
                ExpectedSectionKinds = Array.Empty<string>(),
                ForbiddenSectionTitles = new[] { forbidden },
                RequiredChunkIds = Array.Empty<string>(),
                ForbiddenPatterns = Array.Empty<string>(),
                MinGroundingScore = 0.5,
            });
        }
    }

    private static void RegisterOntologyCompletionTests(GroundingRegressionSuite suite)
    {
        var forbiddenPatterns = new[]
        {
            "This section was auto-completed",
            "Generated by ontology expansion",
            "Inferred entity relationship",
            "Derived business abstraction",
        };

        suite.Register(new SemanticRegressionCase
        {
            CaseId = "anti-ontology-completion",
            Name = "No Ontology Completion",
            Description = "Context sections must not contain LLM-completed ontology patterns.",
            Category = RegressionCategory.Hallucination,
            Query = new Retrieval.Retrieval.RetrievalQuery { Query = "domain entity analysis", TopK = 10 },
            ExpectedSectionKinds = Array.Empty<string>(),
            ForbiddenSectionTitles = Array.Empty<string>(),
            RequiredChunkIds = Array.Empty<string>(),
            ForbiddenPatterns = forbiddenPatterns,
            MinGroundingScore = 0.7,
        });
    }

    private static void RegisterDisconnectedContextTests(GroundingRegressionSuite suite)
    {
        suite.Register(new SemanticRegressionCase
        {
            CaseId = "anti-disconnected-context",
            Name = "No Disconnected Context Sections",
            Description = "Every context section must have at least one source chunk reference.",
            Category = RegressionCategory.Hallucination,
            Query = new Retrieval.Retrieval.RetrievalQuery { Query = "database schema", TopK = 10 },
            ExpectedSectionKinds = Array.Empty<string>(),
            ForbiddenSectionTitles = Array.Empty<string>(),
            RequiredChunkIds = Array.Empty<string>(),
            ForbiddenPatterns = Array.Empty<string>(),
            MinGroundingScore = 0.6,
            MaxUngroundedSections = 0,
            RequireSymbolBinding = true,
        });
    }

    private static void RegisterPropagationOnlyTests(GroundingRegressionSuite suite)
    {
        suite.Register(new SemanticRegressionCase
        {
            CaseId = "anti-propagation-only",
            Name = "No Propagation-Only Entities",
            Description = "Entity nodes must have direct source evidence, not just propagation.",
            Category = RegressionCategory.EntityIntegrity,
            Query = new Retrieval.Retrieval.RetrievalQuery { Query = "entity data access", TopK = 10 },
            ExpectedSectionKinds = Array.Empty<string>(),
            ForbiddenSectionTitles = Array.Empty<string>(),
            RequiredChunkIds = Array.Empty<string>(),
            ForbiddenPatterns = new[] { "propagated entity", "inferred from" },
            MinGroundingScore = 0.7,
        });
    }

    private static void RegisterUngroundedPathTests(GroundingRegressionSuite suite)
    {
        suite.Register(new SemanticRegressionCase
        {
            CaseId = "anti-ungrounded-path",
            Name = "No Ungrounded Traversal Paths",
            Description = "Traversal paths must be based on grounded edges, not inference.",
            Category = RegressionCategory.PathIntegrity,
            Query = new Retrieval.Retrieval.RetrievalQuery { Query = "full request flow", TopK = 10 },
            ExpectedSectionKinds = Array.Empty<string>(),
            ForbiddenSectionTitles = Array.Empty<string>(),
            RequiredChunkIds = Array.Empty<string>(),
            ForbiddenPatterns = new[] { "ungrounded edge", "inferred path" },
            MinGroundingScore = 0.6,
        });
    }
}
